// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF_5IA1OZcABlnvTrhmvkHYPQPF1WNeeE',
    appId: '1:1033770444695:web:2f182d94d9826d744606d2',
    messagingSenderId: '1033770444695',
    projectId: 'fitnesse-c3ded',
    authDomain: 'fitnesse-c3ded.firebaseapp.com',
    databaseURL: 'https://fitnesse-c3ded-default-rtdb.firebaseio.com',
    storageBucket: 'fitnesse-c3ded.appspot.com',
    measurementId: 'G-C4Z976DXQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI94zPMDtLlMqvJHwL6qW2j5coeQin7M0',
    appId: '1:1033770444695:android:dfd54d6df1bcdc884606d2',
    messagingSenderId: '1033770444695',
    projectId: 'fitnesse-c3ded',
    databaseURL: 'https://fitnesse-c3ded-default-rtdb.firebaseio.com',
    storageBucket: 'fitnesse-c3ded.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDju1WbbDt23ig_DRIkwzIlB-qRzzzt2mA',
    appId: '1:1033770444695:ios:6110f9aa65035ae04606d2',
    messagingSenderId: '1033770444695',
    projectId: 'fitnesse-c3ded',
    databaseURL: 'https://fitnesse-c3ded-default-rtdb.firebaseio.com',
    storageBucket: 'fitnesse-c3ded.appspot.com',
    iosBundleId: 'com.example.fitnesseapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDju1WbbDt23ig_DRIkwzIlB-qRzzzt2mA',
    appId: '1:1033770444695:ios:6110f9aa65035ae04606d2',
    messagingSenderId: '1033770444695',
    projectId: 'fitnesse-c3ded',
    databaseURL: 'https://fitnesse-c3ded-default-rtdb.firebaseio.com',
    storageBucket: 'fitnesse-c3ded.appspot.com',
    iosBundleId: 'com.example.fitnesseapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF_5IA1OZcABlnvTrhmvkHYPQPF1WNeeE',
    appId: '1:1033770444695:web:816ffe7c527c6a504606d2',
    messagingSenderId: '1033770444695',
    projectId: 'fitnesse-c3ded',
    authDomain: 'fitnesse-c3ded.firebaseapp.com',
    databaseURL: 'https://fitnesse-c3ded-default-rtdb.firebaseio.com',
    storageBucket: 'fitnesse-c3ded.appspot.com',
    measurementId: 'G-S6BD4BF38F',
  );

}